server:
  path: 8080
  servlet:
    context-path: /identify

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identify.service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

